# Generated by Django 2.1.5 on 2019-01-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quanty', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cadastro', models.CharField(max_length=100, verbose_name='Descrição do Produto')),
                ('preco', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Preço do Produto')),
            ],
        ),
        migrations.AddField(
            model_name='comprador',
            name='comprar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diretoria', verbose_name='Selecionar Produto'),
        ),
    ]
