# Generated by Django 2.1.5 on 2019-01-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprador',
            new_name='Pedido',
        ),
    ]
